### ISSUE TITLE
Resource State enums e.g. VolumeState should have an Error state

### ISSUE THREAD

**Issue by daniellemayne** [greese/dasein-cloud-core#267]
Not sure if this is visible in other clouds but for Openstack some resources can be launched in an Error state. These resources are either not returned in the listBlah calls or are returned in a pending state which they then never leave.
As most actions rely on the state of a resource being something other than Pending (e.g. Running or Stopped), it means we can end up with stuck resources in the cloud that we can't do anything with.
Can we have an Error state for resources so that we could potentially allow only delete/terminate action (as long as the cloud allows it).
Currently Volumes can be available, pending or deleted which does not give an obvious/viable fit for those in an Error state

**Comment by andylyall** [comment]
Merged in 2015.03.1-SNAPSHOT
