### ISSUE TITLE
Supported source/destination types for FirewallRules should be dependent on direction

### ISSUE THREAD

**Issue by erik-johnson** [greese/dasein-cloud-core#317]
The methods listSupportedSourceTypes and listSupportedDestinationTypes in FirewallCapabilities should take in a direction parameter because the list of supported types are often different for different directions. For example in AWS, the supported source types for ingress rules are CIDR and GLOBAL, but for egress rules only GLOBAL sources are allowed.

**Comment by andylyall** [comment]
I'm just revisiting this issue and I've either forgotten or am confused by the statement.
The two methods you've named have explicitly implied direction SourceTypes implying ingress rules and DestinationType implying egress rules.
Is there something else you're looking for?

**Comment by andylyall** [comment]
I've pushed a change for this to the develop branch.
It'll be available after the next major release.
