### ISSUE TITLE
Split out vlanId & subnetId in VMLaunchOptions

### ISSUE THREAD

**Issue by erik-johnson** [greese/dasein-cloud-core#98]
In clouds like azure you can specify a vlan ID or a subnet ID when launching a vm, but right now there is only one field for both IDs, so there are hacks in place to determine if the id is a vlan or a subnet. Let's fix that.

**Comment by unwin** [comment]
signature collision on getInstance() when a string is added to both for withVlanId
reccomend close issue and accept having to use .withVlanId()

**Comment by andylyall** [comment]
Dasein has moved to deal with these things more specifically as factory methods (withSubnetId) rather than overloaded constructors.
